FROM python:alpine3.17

WORKDIR /python-docker

COPY requirements.txt requirements.txt
RUN pip install --upgrade pip

RUN pip3 install flask \
    flask_talisman \
    flask_bcrypt \
    flask_wtf \ 
    wtforms \
    wtforms.validators \
    psycopg2-binary

EXPOSE 8443

COPY ./v1 .

CMD [ "python3", "main.py"]