FROM python:alpine3.17

WORKDIR /python-docker

COPY requirements.txt requirements.txt
RUN pip3 install --upgrade pip

RUN pip3 install flask \
    flask_talisman \
    flask_bcrypt \
    flask_wtf \ 
    wtforms \
    wtforms.validators \
    psycopg2-binary \
    flask_sqlalchemy \
    flask_jwt_extended \
    python_dotenv
    

EXPOSE 8443

COPY . .

CMD [ "python3", "app.py"]